# permissions for end users to edit alamedamachinegroupscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alamedamachinegroupscaler-editor-role
rules:
- apiGroups:
  - autoscaling.containers.ai
  resources:
  - alamedamachinegroupscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.containers.ai
  resources:
  - alamedamachinegroupscalers/status
  verbs:
  - get
