
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - autoscaling.containers.ai
  resources:
  - alamedascalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.containers.ai
  resources:
  - alamedascalers/status
  verbs:
  - get
  - patch
  - update
